fileVersion: 1
id: "8"
mappingDefinitions:
  SRC:
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCDS_SF100TCL
  TARGET:
    database: TRAINING
    schema: ASSIGNMENT
name: Production
type: Environment
